name: Pylint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pylint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        id: lint
        run: |
          # Запускаем pylint и ищем строку, где выводится общий рейтинг.
          score_line=$(pylint $(git ls-files '*.py') | grep "Your code has been rated at" | tail -1)
          echo "Найдена строка со скором: $score_line"

          # Извлекаем числовое значение. 
          # Пример строки:
          # "Your code has been rated at 9.50/10 (previous run: 9.43/10, +0.07)"
          score=$(echo "$score_line" | awk -F " " '{print $6}' | awk -F "/" '{print $1}')
          echo "Pylint score: $score"

          # Передаём score в выходные переменные шага (GITHUB_OUTPUT).
          echo "score=$score" >> "$GITHUB_OUTPUT"

      - name: Generate Pylint badge
        uses: cicirello/gh-badge-builder@v1
        with:
          label: pylint
          message: ${{ steps.lint.outputs.score }}
          color: green
          labelColor: "#555"
          logo: "pylint"
          style: flat
          outputFile: "pylint-badge.svg"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pylint-badge
          path: pylint-badge.svg
